### ISSUE TITLE
Install as regular plugin?

### ISSUE THREAD

**Issue by rsexton404** [chasnz/annotation-tool-for-tinymce-4#2]
This is a super useful tool! Great work! I would love to be able to install it as a regular plug-in in `wp-content` rather than in `wp-includes`. Any advice on how to wrap this as a regular plug-in?

**Comment by clearnz** [comment]
Thank you for the compliment. I developed this some time ago as I couldn't find something similar available. I see there is some documentation on adding buttons to Wordpress’ TinyMCE (https://codex.wordpress.org/TinyMCE). Unfortunately, I’m no longer in a position to spend time on the tool in order to investigate this option, nor can I offer to continue support for the tool if WordPress makes the switch to TinyMCE version 5. Apologies for that.

**Comment by rsexton404** [comment]
No worries! I was able to figure out how to wrap it up in a WordPress plug-in by following some online tutorials. I had to sacrifice the tooltip feature but I just rewired the double-click event to bring up the annotation editor instead. Maybe one of our devs can figure out how to restore the tooltip to its former glory but it's already miles ahead of most annotation plug-ins because it allows us to write longer, multiline comments.
